version: '3'

services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql